apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  tls-crt.pem: {{ .Files.Get "certs/tls-crt.pem" | b64enc }}
  tls-key.pem: {{ .Files.Get "certs/tls-key.pem" | b64enc }}
  {{- if .Values.notary.selfsigned}}
  notary.crt: {{ .Values.notary.selfsignedCert | b64enc }}
  {{- end }}
  root-pub.pem: {{ .Values.notary.rootPubKey | b64enc }}
