apiVersion: v1
entries:
  connaisseur:
  - apiVersion: v2
    appVersion: 2.1.2
    created: "2021-10-15T13:28:02.815483559+02:00"
    description: A Helm chart for the Connaisseur Admission Controller to validate
      container image signatures.
    digest: a480c00ad7aecab0a8398c2355e8e0ac623164b221c71cfb456b5b3be39fa3d3
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.0.0.tgz
    version: 1.0.0
generated: "2021-10-15T13:28:02.814222946+02:00"
